// Sound files PENDING rights review: static requires for the browser playtest build only.
// Generated by scripts/generate-elevator-audio.js --sources from the pack statuses in
// assets/themes/elevator-quest/audio/manifest.json. Only src/themes/elevator-quest/audio/activeSet.web.ts
// imports this file, so native bundles never contain these files (npm run check:bundle proves it).
// Approving a pack is the one-line status change in the manifest, then --sources moves its lines
// to src/themes/elevator-quest/audio/assets.ts.
export const AUDIO_REVIEW_SOURCES: Readonly<Record<string, number>> = {
};
