// Sound files PENDING rights review: static requires for the browser playtest build only.
// Generated by scripts/generate-elevator-audio.js --sources from the pack statuses in
// assets/themes/elevator-quest/audio/manifest.json. Only src/themes/elevator-quest/audio/activeSet.web.ts
// imports this file, so native bundles never contain these files (npm run check:bundle proves it).
// Approving a pack is the one-line status change in the manifest, then --sources moves its lines
// to src/themes/elevator-quest/audio/assets.ts.
export const AUDIO_REVIEW_SOURCES: Readonly<Record<string, number>> = {
  'el1-button-press': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-button-press.wav'),
  'el1-button-light': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-button-light.wav'),
  'el1-door-slide': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-door-slide.wav'),
  'el1-door-meet': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-door-meet.wav'),
  'el1-door-stop': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-door-stop.wav'),
  'el1-brake-release': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-brake-release.wav'),
  'el1-car-travel': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-car-travel.wav'),
  'el1-brake-set': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-brake-set.wav'),
  'el1-machine-room': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-machine-room.wav'),
  'el1-chime': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-chime.wav'),
  'el1-toolbox-open': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-toolbox-open.wav'),
  'el1-toolbox-close': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-toolbox-close.wav'),
  'el1-fan-start': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-fan-start.wav'),
  'el1-gear-turn': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-gear-turn.wav'),
  'el1-radio-static': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-radio-static.wav'),
  'el1-book-open': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-book-open.wav'),
  'el1-telescope-turn': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-telescope-turn.wav'),
  'el1-spring-boing': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-spring-boing.wav'),
  'el1-windmill-turn': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-windmill-turn.wav'),
  'el1-crane-lower': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-crane-lower.wav'),
  'el1-core-hum': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-core-hum.wav'),
  'el1-power-up': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-power-up.wav'),
  'el1-drawer-slide': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-drawer-slide.wav'),
  'el1-golf-putt': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-golf-putt.wav'),
  'el1-answer-right': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-answer-right.wav'),
  'el1-answer-wrong': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-answer-wrong.wav'),
  'el1-discovery': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-discovery.wav'),
  'el1-mission-complete': require('../../assets/themes/elevator-quest/audio/elevenlabs-v1/el1-mission-complete.wav'),
};
