// Sound files for the browser playtest build only: packs PENDING rights review, and approved packs
// marked "bundle": "development" (the synthesized placeholders, ?sound=placeholder) that no production
// profile plays. Generated by scripts/generate-elevator-audio.js --sources from the pack records in
// assets/themes/elevator-quest/audio/manifest.json. Only src/themes/elevator-quest/audio/activeSet.web.ts
// imports this file, so native bundles never contain these files (npm run check:bundle proves it).
// Approving a pack is the one-line status change in the manifest, then --sources moves its lines
// to src/themes/elevator-quest/audio/assets.ts.
export const AUDIO_REVIEW_SOURCES: Readonly<Record<string, number>> = {
  'button-click': require('../../assets/themes/elevator-quest/audio/button-click.wav'),
  'button-confirm': require('../../assets/themes/elevator-quest/audio/button-confirm.wav'),
  'door-motor-loop': require('../../assets/themes/elevator-quest/audio/door-motor-loop.wav'),
  'door-thud': require('../../assets/themes/elevator-quest/audio/door-thud.wav'),
  'door-settle': require('../../assets/themes/elevator-quest/audio/door-settle.wav'),
  'motor-start': require('../../assets/themes/elevator-quest/audio/motor-start.wav'),
  'travel-loop': require('../../assets/themes/elevator-quest/audio/travel-loop.wav'),
  'motor-slow': require('../../assets/themes/elevator-quest/audio/motor-slow.wav'),
  'arrival-stop': require('../../assets/themes/elevator-quest/audio/arrival-stop.wav'),
  'arrival-chime': require('../../assets/themes/elevator-quest/audio/arrival-chime.wav'),
  'ambient-machinery': require('../../assets/themes/elevator-quest/audio/ambient-machinery.wav'),
  'overload-tone': require('../../assets/themes/elevator-quest/audio/overload-tone.wav'),
  'power-restore': require('../../assets/themes/elevator-quest/audio/power-restore.wav'),
  'completion': require('../../assets/themes/elevator-quest/audio/completion.wav'),
};
