// Production asset map for the elevator sound set: every file of an APPROVED pack (manifest.json).
// Generated by scripts/generate-elevator-audio.js --sources; audio.test.ts keeps it in step with the
// manifest. Metro bundles each file; nothing is fetched at runtime. Files of a pack pending review
// are listed in src/devtools/audioReviewSources.ts instead, so production bundles never carry them.
export const AUDIO_ASSETS: Record<string, number> = {
  'button-click': require('../../../../assets/themes/elevator-quest/audio/button-click.wav'),
  'button-confirm': require('../../../../assets/themes/elevator-quest/audio/button-confirm.wav'),
  'door-motor-loop': require('../../../../assets/themes/elevator-quest/audio/door-motor-loop.wav'),
  'door-thud': require('../../../../assets/themes/elevator-quest/audio/door-thud.wav'),
  'door-settle': require('../../../../assets/themes/elevator-quest/audio/door-settle.wav'),
  'motor-start': require('../../../../assets/themes/elevator-quest/audio/motor-start.wav'),
  'travel-loop': require('../../../../assets/themes/elevator-quest/audio/travel-loop.wav'),
  'motor-slow': require('../../../../assets/themes/elevator-quest/audio/motor-slow.wav'),
  'arrival-stop': require('../../../../assets/themes/elevator-quest/audio/arrival-stop.wav'),
  'arrival-chime': require('../../../../assets/themes/elevator-quest/audio/arrival-chime.wav'),
  'ambient-machinery': require('../../../../assets/themes/elevator-quest/audio/ambient-machinery.wav'),
  'overload-tone': require('../../../../assets/themes/elevator-quest/audio/overload-tone.wav'),
  'power-restore': require('../../../../assets/themes/elevator-quest/audio/power-restore.wav'),
  'completion': require('../../../../assets/themes/elevator-quest/audio/completion.wav'),
};
